### Generate Text
# This request generates text based on a given prompt.
GET http://0.0.0.0:8000/generate-text/
Content-Type: application/json
Query: prompt=What is atomic number of oxygen?

###

### List Models
# This request retrieves a list of models that support content generation.
GET http://0.0.0.0:8000/list-models/
Content-Type: application/json

###
